project:
  type: book
  output-dir: docs

book:
  title: "Komputasi Probabiltas dan Statistika"
  author: "Muhammad Zulfa Fauzan Nurhuda (18224064)"
  date: today
  date-format: "DD MMMM YYYY"
  chapters:
    - index.qmd
    - contents/intro.qmd
    - assignments/w01/quiz.qmd
    - submissions/w01/laporan.qmd
    - assignments/w02/quiz.qmd
    - submissions/w02/laporan.qmd
    - assignments/w03/quiz.qmd
    - submissions/w03/laporan.qmd
    - assignments/w04/quiz.qmd
    - submissions/w04/laporan.qmd
    - assignments/w05/quiz.qmd
    - submissions/w05/laporan.qmd
    - assignments/w06/quiz.qmd
    - submissions/w06/laporan.qmd
    - assignments/w07/quiz.qmd
    - submissions/w07/laporan.qmd
    - assignments/w08/quiz.qmd
    - submissions/w08/laporan.qmd
    - assignments/w09/quiz.qmd
    - submissions/w09/laporan.qmd
    - assignments/w10/quiz.qmd
    - submissions/w10/laporan.qmd
    - assignments/w11/quiz.qmd
    - submissions/w11/laporan.qmd
    - assignments/w12/quiz.qmd
    - submissions/w12/laporan.qmd
    - assignments/w13/quiz.qmd
    - submissions/w13/laporan.qmd
    - assignments/w14/quiz.qmd
    - submissions/w14/laporan.qmd
    - contents/summary.qmd
    - contents/references.qmd

bibliography: contents/references.bib

format:
  html:
    theme: superhero
    toc: true
    toc-depth: 5
    smooth-scroll: true
    code-copy: true
    number-sections: false
execute:
  echo: false
  warning: false
  message: false
